
server:
  port: 1234

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hrms?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect #dialect(ngon ngu) cho hibnate tuongw tac csdl
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "hailam2034@gmail.com"
    password: "zrjz dhty umva fzvr"# Rất quan trọng!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  frontend:
    url: "https://l16msdnh-3000.asse.devtunnels.ms/"
  jwt:
    secret: 'DayLaMotChuAiBiMatMoiRatDaiVaAnToanHonChuoiCuRatNhieu_Phai64KyTuNhe'
    expiration-ms: 2592000000 # 30 ngày (30 * 24 * 60 * 60 * 1000)


api:
  prefix: /api/v1